name: Deployment to Koyeb (CLI)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Koyeb CLI
        run: |
          curl https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh

      - name: Configure and Redeploy
        run: |
          echo "token: ${{ secrets.KOYEB_API_TOKEN }}" > $HOME/.koyeb.yaml
          /home/runner/.koyeb/bin/koyeb service redeploy bcca8048-7132-4782-a98b-2a3835d96664